# Generated by Django 6.0 on 2025-12-19 09:18

from django.db import migrations


def create_profiles(apps, schema_editor):
    Profile = apps.get_model("users", "Profile")
    User = apps.get_model("users", "User")

    users_without_profiles = User.objects.filter(profile__isnull=True)
    new_profiles = [
        Profile(user=user)
        for user in users_without_profiles
    ]

    if new_profiles:
        Profile.objects.bulk_create(new_profiles)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.RunPython(create_profiles, migrations.RunPython.noop)
    ]
